train {
    #每4轮输出一次
    print_interval = 10
    #每一千轮保存一次模型
    save_interval = 3000
    #每一千轮可视化一次
    vis_interval = 1000
    #每1000轮验证一次
    eval_interval = 3000
    #epoch数
    num_epochs = 4
    #epoch数
    num_epoch = 4
    #每个epoch遍历dataset次数
    num_epoch_repeats = 50
    #累积梯度次数
    accu_grad = 1
    #背景辐射场优化次数
    background_epochs = 1
    #前景辐射场优化次数
    foreground_epochs = 0
    #全部辐射场优化次数
    all_epochs = 1
    
}
model {
    use_xyz = True
    canon_xyz = False
    use_code = True
    use_viewdirs = True
    type=sngp
    use_code_viewdirs = False
    code {
        num_freqs = 8
        include_input = True
    }
    mlp_coarse {
        type = resnet
        n_blocks = 5    
        combine_layer = 3
        combine_type = average
        d_hidden = 512
    }
    mlp_fine {
        type = resnet
        n_blocks = 5
        combine_layer = 3
        combine_type = average
        d_hidden = 512
    }
    mlp_refl {
        type = resnet
        n_blocks = 5
        combine_layer = 3
        combine_type = average
        d_hidden = 512
    }
}
renderer {
    n_coarse = 128 
    n_fine = 32
    n_fine_depth = 32
    depth_std = 0.01
    sched = []
    white_bkgd = False
}
loss {
    rgb {
        use_l1 = False
    }
    rgb_fine {
        use_l1 = False
    }
    alpha {
        # lambda_alpha = 0.0001
        lambda_alpha = 0.0
        clamp_alpha = 100
        init_epoch = 5
    }
    lambda_coarse = 1.0  
    lambda_fine = 1.0
}